[project]
name = "repl-nix-crawlstatsanalyzer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "streamlit-aggrid>=1.0.5",
    "streamlit>=1.40.1",
]
